### ISSUE TITLE
Long paragraphs

### ISSUE THREAD

**Issue by ldutra** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#15]
Would it be interesting to have shorter paragraphs?  Specially when one is not fluent in the alphabet, parsing the initial paragraph, for instance, is quite painful.

**Comment by seumasjeltzz** [comment]
I wonder, and have often wondered, if the solution, such as it is, is to create lessons that sit between 0 and 1. Because there's a different alphabet, and because students who are starting from absolutely zero need to come to terms with that before they can begin to read, a "unit zero" strikes me as a desideratum.

**Comment by ldutra** [comment]
Granted.  But that creates other issues such as pronounciation, as most of us aren’t skilled in IPA, many not even native English speakers if one uses English as a base for denoting pronounciation.  Duolingo works with either voice recordings or speech synthesis, but that jumps from a simple, nice text document to a fully automated course.

I would split the issue of learning the alphabet (and diacrictics) in another issue, and keep this about paragraph length.  I have been doing modern Greek Duolingo for months now, so I am fairly confident in the alphabet (but not in κοινή or αρχαία prounciation), but still shorter paragraphs would help a lot.

**Comment by ldutra** [comment]
Just generated a new lgpsi.epub from current source, thanks a lot for the paragraph breaks!
