### ISSUE TITLE
C ἐστὶ or C ἐστι

### ISSUE THREAD

**Issue by na4zagin3** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#43]
> τὸ C ἐστὶ γράμμα Ῥωμαϊκόν.
https://github.com/seumasjeltzz/LinguaeGraecaePerSeIllustrata/blob/c25f07bb74cf7f8d22af8e0113f45c2f14b66df6/src/001.md#L31

I'm not sure how “C” was called in Ancient greek.  If it was called κή, κῆ, κεί or κεῖ since C was _cē_ in Latin, shouldn't it be “τὸ _κεῖ_ ἐστι”?  Otherwise, was it perhaps “κε” with an epsilon, resulting “τὸ _κ’_ ἐστί”?

**Comment by seumasjeltzz** [comment]
Hmm, you raise an interesting question; I'm unaware if we have any written-out examples of how Greeks speaking Greek named Latin letters. I suppose if they directly took them from Latin, κή or κῆ is most likely, rather than an epsilon, though if it were an epsilon, elision is not obligatory.

I think in terms of resolving the accent question though, the best thing would be to search for an example of an individual Greek letter pronounced as a monosyllable, e.g. μῦ, νῦ, πῖ, in this kind of context. I'll take a look at the corpus data.

**Comment by seumasjeltzz** [comment]
Running some text searches on μ, ν, ξ, π, ψ, χ, ψ followed by ἐστιν, I find a few examples each for ἐστίν and ἐστιν after an individual letter, all pretty much in Aelius Herodianus. I don't think I'm likely to change the text to present a pronunciation of the letter though.

**Comment by na4zagin3** [comment]
Thank you for checking!
